export const imageUrl = "https://image.tmdb.org/t/p/original"
export const baseURl = 'https://api.themoviedb.org/3'
export const apikey = "b999d9fa858536ad35453910cf2ad2e3"
export const trendingURL = `/trending/all/day?api_key=${apikey}`
export const actionURL = `/discover/movie?api_key=${apikey}&with_genres=28`
export const comedyURL = `/discover/movie?api_key=${apikey}&with_genres=35`
export const thrillerURL = `/discover/movie?api_key=${apikey}&with_genres=53`
export const horrorURL = `/discover/movie?api_key=${apikey}&with_genres=27`
export const romanceURL = `/discover/movie?api_key=${apikey}&with_genres=10749`
export const animationURL = `/discover/movie?api_key=${apikey}&with_genres=16`